services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: echange_de_temps
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"   # ← changé ici (avant : "5432:5432")

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=echange_de_temps
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432  

volumes:
  postgres_data: