# Generated by Django 5.2.17 on 2026-09-11 14:28

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        TrigramExtension(),
    ]