# Generated by Django 5.2.17 on 2026-09-18 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0001_initial'),
    ]

    operations = [
    ]
