# Generated by Django 5.2.17 on 2026-09-18 14:19

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0002_enable_pg_trgm'),
    ]

    operations = [
                TrigramExtension(),
    ]
